#include <QtWidgets/QApplication.h>
#include <QtWidgets/QPushbutton.h>
#include <QtWidgets/QMainWindow>
#include <QtGui/QtGui>
#include <QtWidgets/QtWidgets>
#include <QtCore/QtCore>
#include <QtGui/QMouseEvent>
#include <QtWidgets/QLabel>
#include <QtWidgets/qbuttongroup.h>
#include <QtGui/QPainter>
#include <QtCore/QElapsedTimer>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTableWidgetItem>
#include <QtWidgets/QMenu>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QAction>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QVBoxLayout>