#include <QtWidgets/QApplication>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QCheckBox>
#include <QtCore/QArrayData>
#include <QtWidgets/QLineEdit>
#include <QtCore/QObject>
#include <QtGui/QtGui>
#include <QtWidgets/QWidget>
#include <QtCore/QtCore>
#include <QtGui/QMouseEvent>
#include <QtWidgets/QLabel>
#include <QtWidgets/QButtonGroup>
#include <QtGui/QPainter>
#include <QtCore/QElapsedTimer>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTableWidgetItem>
#include <QtWidgets/QMenu>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QAction>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QVBoxLayout>