#include <qt6/QtWidgets/QApplication.h>
#include <qt6/QtWidgets/QPushbutton.h>
#include <qt6/QtWidgets/QMainWindow>
#include <qt6/QtGui/QGuiApplication>
#include <qt6/QtWidgets/QWidget>
#include <qt6/QtCore/QtCore>
#include <qt6/QtGui/QtGui>
#include <qt6/QtWidgets/QLabel>
#include <qt6/QtWidgets/qbuttongroup.h>
#include <qt6/QtGui/QPainter>
#include <qt6/QtCore/QElapsedTimer>
#include <qt6/QtWidgets/QMenuBar>
#include <qt6/QtWidgets/QCheckBox>
#include <qt6/QtWidgets/QTableWidget>
#include <qt6/QtWidgets/QTableWidgetItem>
#include <qt6/QtWidgets/QMenu>
#include <qt6/QtWidgets/QHeaderView>
#include <qt6/QtWidgets/QDockWidget>
#include <qt6/QtWidgets/QVBoxLayout>